#!/bin/bash
# This script is responsible for generating the zoiper client config file for a 
# deployment on a March-Hare Communications Collective Operator Distribution.

HOME=/root
ZOIPER_CONF=$HOME/.zoiper/zoiper.conf

ASTERISK_SERVER=10.66.6.1
SIP_USER=101
SIP_PASSWORD=welcome
ORGANIZATION=ChickenCoup
SIP_NAME=MeowFace

# Modify the zoiper config file to be able to log into the deployment voice server
function update_zoiper_config {
  sed -i -e "s;\(<check_for_updates>\)[0-9];\10;" $ZOIPER_CONF
	sed -i -e "s;<default_account/>;<default_account>$ORGANIZATION</default_account>;" $ZOIPER_CONF
	sed -i -e "s;<accounts/>;<accounts> \
	     <account> \
	       <tech>0</tech> \
	       <name>$ORGANIZATION</name> \
	       <host>$ASTERISK_SERVER</host> \
	       <username>$SIP_USER</username> \
	       <password>$SIP_PASSWORD</password> \
	       <context>$ASTERISK_SERVER</context> \
	       <callerid>$SIP_NAME</callerid> \
	       <number></number> \
	       <use_outbound_proxy>0</use_outbound_proxy> \
	       <dtmf_style>1</dtmf_style> \
	       <register_on_startup>1</register_on_startup> \
	       <do_not_play_ringback_tones>0</do_not_play_ringback_tones> \
	       <use_stun>1</use_stun> \
	       <stun_host></stun_host> \
	       <stun_port>0</stun_port> \
	       <stun_refresh_period>0</stun_refresh_period> \
	       <custom_codecs>0</custom_codecs> \
	     </account> \
	</accounts>;" $ZOIPER_CONF
}

update_zoiper_config
